#!/usr/bin/env bash
# Generate the enterprise container-per-user compose file (roadmap T3.5).
#
# Usage: scripts/generate_enterprise_compose.sh <user_id> [<user_id> ...]
#
# Renders docker/docker-compose.enterprise.yaml with ONE service per tenant
# user. Container names and host ports are derived from a consistent hash of
# the user_id (sha256, first 8 hex chars) — the same user_id always maps to
# the same container and port. NEVER run two services for the same user.
set -euo pipefail
cd "$(dirname "$0")/.."

IMAGE="${ENTERPRISE_IMAGE:-ghcr.io/open-assistants-lab/assistant:latest}"
PORT_BASE="${ENTERPRISE_PORT_BASE:-8100}"
OUT="docker/docker-compose.enterprise.yaml"
USERS_DIR="docker/enterprise/users"

mkdir -p "$USERS_DIR"

cat > "$OUT" << 'HEADER'
# GENERATED by scripts/generate_enterprise_compose.sh — container-per-tenant-user.
# One container per TENANT USER; never two services for the same user_id
# (per-user SQLite/ChromaDB are single-writer; AGENTS.md).
#
# Auth models: per-container API_KEY (set in each user's .env) OR
# PER_USER_AUTH=true on every container with keys minted once centrally.
services:
HEADER

for user in "$@"; do
  shard=$(printf '%s' "$user" | sha256sum | cut -c1-8)
  name="assistant-ent-${shard}"
  port=$(( PORT_BASE + 16#$(printf "%s" "$shard" | tail -c 2) % 100 ))
  mkdir -p "$USERS_DIR/${user}/data" "$USERS_DIR/${user}"

  if [ ! -f "$USERS_DIR/${user}/.env" ]; then
    cat > "$USERS_DIR/${user}/.env" << ENVEOF
# Auth model A (shared): per-container deployment key
API_KEY=change-me-$(printf '%s' "$user" | sha256sum | cut -c1-12)
# Auth model B (per-user keys): uncomment on every container instead
# PER_USER_AUTH=true
ENVEOF
  fi

  cat >> "$OUT" << SERVICEEOF

  assistant-ent-${shard}:
    image: ${IMAGE}
    container_name: assistant-ent-${shard}
    command: ["uv", "run", "assistant", "http"]
    ports:
      - "127.0.0.1:${port}:8080"
    environment:
      API_HOST: "0.0.0.0"
      API_PORT: "8080"
      DEPLOYMENT_DATA_ROOT: /app/data
      DEPLOYMENT_DATA_PATH: /app/data
      DEPLOYMENT_MODE: enterprise
    env_file:
      - ./enterprise/users/${user}/.env
    volumes:
      - ./enterprise/users/${user}/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
SERVICEEOF
  echo "user ${user} -> container assistant-ent-${shard} (port ${port})"
done

echo "wrote ${OUT}"